version: "3.7"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: perpus
    container_name: perpus-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - perpus
  nginx:
    image: nginx:alpine
    container_name: perpus-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./nginx:/etc/nginx/conf.d/
    networks:
      - perpus

networks:
  perpus:
    driver: bridge